name: Deploy to HF Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/Noah-Wallace/GenBot hf-space
          rsync -av --exclude '.git' ./ hf-space/
          cd hf-space
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync from github" || echo "No changes to commit"
          git push https://x-access-token:${HF_TOKEN}@huggingface.co/spaces/Noah-Wallace/GenBot main
