name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # Runs whenever you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Sync to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "noahwallace9044@gmail.com"
          git config --global user.name "Noah-Wallace"
          git clone https://huggingface.co/spaces/noahwallace/GenBot hf-space
          rsync -av --exclude='.git' ./ hf-space/
          cd hf-space
          git add .
          git commit -m "Sync from GitHub"
          git push https://NoahWallace:${HF_TOKEN}@huggingface.co/spaces/noahwallace/GenBot HEAD:main
